### ISSUE TITLE
The file "screencasts/settings_shortcuts.md\n.md" is broken

### ISSUE THREAD

**Issue by Paebbels** [sigasi/sigasi_insights#1]
Hello,

the Sigasi Insights repository can not be checked out on Windows platforms, because the file `screencasts/settings_shortcuts.md\n.md` is broken. I assume it was committed on a Linux or OS X machine with a line linebreake in the name. See the `\n` and doubled extension `.md`.

Regards
    Patrick

**Comment by heeckhau** [comment]
Thanks for reporting. This is fixed now.
