### ISSUE TITLE
css problem on homepage

### ISSUE THREAD

**Issue by tivaliy** [sigasi/sigasi_insights#9]
There is a small css problem in displaying main page (homepage) of http://insights.sigasi.com/ in Firefox (52.0.2 (64-bit)) and Chrome (Version 57.0.2987.133 (64-bit))

![sigasi_demo](https://cloud.githubusercontent.com/assets/12431595/24588067/1e17c2a6-17ca-11e7-947e-73c430b5dd91.png)

**Comment by hildegoossens78** [comment]
Dear Vitalii,

Thank you for letting us know, we appreciate your input. I have added it to
our list and we will try to fix this asap.

Kind regards,
Hilde

*Hilde Goossens*   *– Sales Service Manager*

T  + 32 9 265 71 38

hilde.goossens@sigasi.com

M + 32 472 61 14 57

www.sigasi.com

Sigasi nv - Kerkstraat 108, 9050 Gentbrugge, Belgium
--------------------------------------------------------------------

[image:
https://ci6.googleusercontent.com/proxy/3ii7N0yYfah2bZXFfPznvq_hAE9jPvTX9JNynD3zvWYpd7dIe-579UIUP5X-ZNeukxi8sWpThtVN6tEuYFji6V2JX-CMkvgjmQEHhXEf7Kl7CVZp=s0-d-e1-ft#http://xpublic.cantilis.be/sigasi/handtekening/sigasi_logo.png]

**Comment by tivervac** [comment]
This has since been fixed
